project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!*.scraps.qmd"
    - "!*.test.qmd"
    - "!*.progress.qmd"
    - "!*.wip.qmd"
    - "!units_old/"
website:
  title: "CS-108-A (Introduction to Computing) at Calvin University"
  navbar:
    search: true
  sidebar:
    contents:
      - "index.qmd"
      - "lab-instructions.qmd"
      - "tips-resources.qmd"
      - "feedback.qmd"
      - "class-demonstrations.qmd"
      - file: "finalproject.qmd"
        icon: "suitcase-lg"
      - auto: "classes/"
        icon: "person-workspace"
      - section: "Units"
        contents:
          - section: "1. Introduction"
            contents: 
              - section: "Concepts"
                icon: "book-half"
                contents:
                  - text: "1.1 Program"
                    file: "units/01/program.qmd"
                  - text: "1.2 Computation"
                    file: "units/01/computation.qmd"
                  - text: "1.3 Code"
                    file: "units/01/code.qmd"
                  - text: "1.4 Objects and Variables"
                    file: "units/01/objects-variables.qmd"
                  - text: "1.5 Assignments"
                    file: "units/01/assignments.qmd"
                  - text: "1.6 Input/Output"
                    file: "units/01/input-output.qmd"
                  - text: "1.7 Running Python"
                    file: "units/01/running-python.qmd"
              - section: "Activities"
                icon: "pencil"
                contents:
                  - text: "Presentations"
                    file: "units/01/activities/presentations.qmd"
                  - text: "Pictionary Example"
                    file: "units/01/activities/pictionary.qmd"
          - section: "2. Expressions"
            contents: 
              - section: "Concepts"
                icon: "book-half"
                contents:
                  - text: "2.1 Operators"
                    file: "units/02/operators.qmd"
                  - text: "2.2 Overflow"
                    file: "units/02/overflow.qmd"
                  - text: "2.3 Constants"
                    file: "units/02/constants.qmd"
                  - text: "2.4 Math module"
                    file: "units/02/math-module.qmd"
                  - text: "2.5 Random numbers"
                    file: "units/02/random-module.qmd"
                  - text: "2.6 Comments"
                    file: "units/02/comments.qmd"
                  - text: "2.7 Programming style"
                    file: "units/02/programming-style.qmd"
              - section: "Activities"
                icon: "pencil"
                contents:
                  - text: "Computers are stupid?"
                    file: "units/02/activities/computers-are-stupid.qmd"
                  - text: "Hospitable-code"
                    file: "units/02/activities/hospitable-code.qmd"
          - section: "3. Data types"
            contents: 
              - section: "Concepts"
                icon: "book-half"
                contents:
                  - text: "3.1 Built-in Types"
                    file: "units/03/built-in-types.qmd"
                  - text: "3.2 Object Methods"
                    file: "units/03/object-methods.qmd"
                  - text: "3.3 Tuples"
                    file: "units/03/tuples.qmd"
                  - text: "3.4 Strings"
                    file: "units/03/strings.qmd"
                  - text: "3.5 Lists"
                    file: "units/03/lists.qmd"
                  - text: "3.6 Dictionaries"
                    file: "units/03/dictionaries.qmd"
              - section: "Activities"
                icon: "pencil"
                contents:
                  - text: "Encoding Information"
                    file: "units/03/activities/encoding-information.qmd"
                  - text: "The world of 0's and 1's"
                    file: "units/03/activities/information-society.qmd"
          - section: "4. Branching"
            contents: 
              - section: "Concepts"
                icon: "book-half"
                contents:
                  - text: "4.1 If statement"
                    file: "units/04/if.qmd"
                  - text: "4.2 If-else"
                    file: "units/04/if-else.qmd"
                  - text: "4.3 Multi-way selection"
                    file: "units/04/elif.qmd"
                  - text: "4.4 Nested ifs"
                    file: "units/04/nesting-ifs.qmd"
                  - text: "4.5 Comparison Operators"
                    file: "units/04/comparison-ops.qmd"
                  - text: "4.6 Boolean Operators"
                    file: "units/04/boolean-ops.qmd"
                  - text: "4.7 Membership Operators"
                    file: "units/04/membership-ops.qmd"
                  - text: "4.8 Discrimination"
                    file: "units/04/discrimination.qmd"
                  - text: "4.7 Algorithmic Intelligence"
                    file: "units/04/intelligence.qmd"
              - section: "Activities"
                icon: "pencil"
                contents:
                  - text: "Exercises 1"
                    file: "units/04/activities/exercises1.qmd"
                  - text: "Exercises 2"
                    file: "units/04/activities/exercises2.qmd"
          - section: "5. Repetition"
            contents: 
              - section: "Concepts"
                icon: "book-half"
                contents:
                  - text: "5.1 Repetition Statements"
                    file: "units/05/repetition-statements.qmd"
                  - text: "5.2 While Loops"
                    file: "units/05/while.qmd"
                  - text: "5.3 Break and continue"
                    file: "units/05/break-continue.qmd"
                  - text: "5.4 Nested loops"
                    file: "units/05/nested-loops.qmd"
                  - text: "5.5 For loops"
                    file: "units/05/for.qmd"
                  - text: "5.6 Ranges"
                    file: "units/05/ranges.qmd"
                  - text: "5.7 List Comprehensions"
                    file: "units/05/list-comprehensions.qmd"
                  - text: "5.8 The Halting Problem"
                    file: "units/05/the-halting-problem.qmd"
                  - text: "5.9 List Comprehensions"
                    file: "units/05/ethics-of-automation.qmd"
              - section: "Activities"
                icon: "pencil"
                contents:
                  - text: "Tile Drawing"
                    file: "units/05/activities/tile-drawing.qmd"
                  - text: "Accumulators"
                    file: "units/05/activities/accumulators.qmd"
                  - text: "Flags"
                    file: "units/05/activities/flags.qmd"
          - section: "6. Functions"
            contents: 
              - section: "Concepts"
                icon: "book-half"
                contents:
                  - text: "6.1 Abstraction"
                    file: "units/06/abstraction.qmd"
                  - text: "6.2 Functions"
                    file: "units/06/functions.qmd"
                  - text: "6.3 Parameters"
                    file: "units/06/parameters.qmd"
                  - text: "6.4 Return"
                    file: "units/06/return.qmd"
                  - text: "6.5 Variable scope"
                    file: "units/06/scope.qmd"
                  - text: "6.6 Docstrings"
                    file: "units/06/docstrings.qmd"
              - section: "Activities"
                icon: "pencil"
                contents:
                  - text: "Common errors"
                    file: "units/06/activities/common-errors.qmd"
          - section: "7. Classes"
            contents: 
              - section: "Concepts"
                icon: "book-half"
                contents:
                  - text: "7.1 Object-Oriented Programming"
                    file: "units/07/oop.qmd"
                  - text: "7.2 The constructor method"
                    file: "units/07/constructor.qmd"
                  - text: "7.3 The self argument"
                    file: "units/07/self.qmd"
                  - text: "7.4 Class methods and variables"
                    file: "units/07/class-methods.qmd"
                  - text: "7.5 The __str__ method"
                    file: "units/07/str-method.qmd"
                  - text: "7.6 Operator overloading"
                    file: "units/07/operator-overloading.qmd"
                  - text: "7.7 Inheritance"
                    file: "units/07/inheritance.qmd"
                  - text: "7.8 Semantic Web"
                    file: "units/07/semantic-web.qmd"
                  - text: "7.9 Network power"
                    file: "units/07/network-power.qmd"
              - section: "Activities"
                icon: "pencil"
                contents:
                  - text: "Card game"
                    file: "units/07/activities/a-card-game.qmd"
                  - text: "Shapes and areas"
                    file: "units/07/activities/shapes-and-areas.qmd"
  page-navigation: true
  
format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-depth: 4
    toc-expand: 4 
    toc_float: true